services:
  postgres:
    image: postgres:18-alpine
    container_name: eclipse-postgres
    restart: unless-stopped
    mem_limit: 384m
    environment:
      POSTGRES_DB: eclipse
      POSTGRES_USER: eclipse
      POSTGRES_PASSWORD: eclipse@1234567890
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    container_name: eclipse-redis
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    mem_limit: 128m
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: