spring:
  docker:
    compose:
      file: ../docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/eclipse
    username: eclipse
    password: eclipse@1234567890
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[com.eclipse]": DEBUG
    "[org.springframework.web]": DEBUG