# File: backend/src/main/resources/application.yml
spring:
  application:
    name: eclipse-backend
  profiles:
    active: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never